name: 'nyc_taxi_pipeline'
version: '1.0.0'

profile: 'nyc_taxi_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_taxi_pipeline:
    silver:
      +schema: silver
      +materialized: table
      +file_format: delta
    gold:
      +schema: gold
      +materialized: table
      +file_format: delta