version: 2

models:
  - name: silver_trips
    description: "Datos limpios y normalizados NYC Taxi julio 2016 - 2019"
    columns:
      - name: trip_id
        description: "ID único por viaje generado con MD5"
        tests:
          - not_null
          - unique:
              config:
                severity: warn

      - name: vendor_id
        description: "ID del proveedor de taxi (-1=Desconocido, 1=Creative Mobile, 2=VeriFone)"
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, -1]

      - name: pickup_datetime
        description: "Fecha y hora de recogida"
        tests:
          - not_null

      - name: dropoff_datetime
        description: "Fecha y hora de destino"
        tests:
          - not_null

      - name: passenger_count
        description: "Número de pasajeros (1-6)"
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6]

      - name: payment_type
        description: "Tipo de pago (-1=desconocido, 1=tarjeta, 2=efectivo, 3=sin cargo, 4=disputa)"
        tests:
          - accepted_values:
              values: [1, 2, 3, 4, 5, -1]

      - name: pu_location_id
        description: "ID de zona de recogida"
        tests:
          - not_null

      - name: do_location_id
        description: "ID de zona de destino"
        tests:
          - not_null